id = "faber-romanus"
name = "Faber Romanus"
description = "Latin programming language support"
version = "0.1.0"
schema_version = 1
authors = ["Ian Zepp <ian@ianzepp.com>"]
repository = "https://github.com/ianzepp/faber-romanus"

[grammars.faber-romanus]
repository = "https://github.com/ianzepp/faber-romanus"
rev = "69aec430d9f8cf307ca06227feb449cc5b8a802e"
path = "grammars/faber-romanus"
