name = "Faber Romanus"
grammar = "faber-romanus"
path_suffixes = ["fab"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["_"]
